// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsfawnrryhsezfjayesz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZmF3bnJyeWhzZXpmamF5ZXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzYzMjUsImV4cCI6MjA2MjM1MjMyNX0.xOIswi55zMWT_lfJYHoeudXyxSVGQjjihOK6zjV14jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);